spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: yobi
    password: alfabeta
    platform: mysql
    url: jdbc:mysql://employeedb.cbk6cs3emo0c.us-east-2.rds.amazonaws.com:3306/employeedb?enabledTLSProtocols=TLSv1.2
